/*
 * Accounting API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package model

import (
	"time"
)

type Invoice struct {

	// See Invoice Types
	Type_ string `json:"Type"`

	// See LineItems
	LineItems []LineItem `json:"LineItems"`

	// Date invoice was issued – YYYY-MM-DD. If the Date element is not specified it will default to the current date based on the timezone setting of the organisation
	Date time.Time `json:"Date,omitempty"`

	// Date invoice is due – YYYY-MM-DD
	DueDate time.Time `json:"DueDate,omitempty"`

	// Line amounts are exclusive of tax by default if you don’t specify this element. See Line Amount Types
	LineAmountTypes string `json:"LineAmountTypes,omitempty"`

	// ACCREC – Unique alpha numeric code identifying invoice (when missing will auto-generate from your Organisation Invoice Settings) (max length = 255)
	InvoiceNumber string `json:"InvoiceNumber,omitempty"`

	// ACCREC only – additional reference number (max length = 255)
	Reference string `json:"Reference,omitempty"`

	// See BrandingThemes
	BrandingThemeID string `json:"BrandingThemeID,omitempty"`

	// URL link to a source document – shown as “Go to [appName]” in the Xero app
	Url string `json:"Url,omitempty"`

	// The currency that invoice has been raised in (see Currencies)
	CurrencyCode string `json:"CurrencyCode,omitempty"`

	// The currency rate for a multicurrency invoice. If no rate is specified, the XE.com day rate is used. (max length = [18].[6])
	CurrencyRate float32 `json:"CurrencyRate,omitempty"`

	// See Invoice Status Codes
	Status string `json:"Status,omitempty"`

	// Boolean to set whether the invoice in the Xero app should be marked as “sent”. This can be set only on invoices that have been approved
	SentToContact bool `json:"SentToContact,omitempty"`

	// Shown on sales invoices (Accounts Receivable) when this has been set
	ExpectedPaymentDate string `json:"ExpectedPaymentDate,omitempty"`

	// Shown on bills (Accounts Payable) when this has been set
	PlannedPaymentDate string `json:"PlannedPaymentDate,omitempty"`

	// Total of invoice excluding taxes
	SubTotal float32 `json:"SubTotal,omitempty"`

	// Total tax on invoice
	TotalTax float32 `json:"TotalTax,omitempty"`

	// Total of Invoice tax inclusive (i.e. SubTotal + TotalTax). This will be ignored if it doesn’t equal the sum of the LineAmounts
	Total float32 `json:"Total,omitempty"`

	// Total of discounts applied on the invoice line items
	TotalDiscount float32 `json:"TotalDiscount,omitempty"`

	// Xero generated unique identifier for invoice
	InvoiceID string `json:"InvoiceID,omitempty"`

	// boolean to indicate if an invoice has an attachment
	HasAttachments bool `json:"HasAttachments,omitempty"`

	// See Payments
	Payments []Payment `json:"Payments,omitempty"`

	// See Prepayments
	Prepayments []Prepayment `json:"Prepayments,omitempty"`

	// See Overpayments
	Overpayments []Overpayment `json:"Overpayments,omitempty"`

	// Amount remaining to be paid on invoice
	AmountDue float32 `json:"AmountDue,omitempty"`

	// Sum of payments received for invoice
	AmountPaid float32 `json:"AmountPaid,omitempty"`

	// The date the invoice was fully paid. Only returned on fully paid invoices
	FullyPaidOnDate time.Time `json:"FullyPaidOnDate,omitempty"`

	// Sum of all credit notes, over-payments and pre-payments applied to invoice
	AmountCredited float32 `json:"AmountCredited,omitempty"`

	// Last modified date UTC format
	UpdatedDateUTC time.Time `json:"UpdatedDateUTC,omitempty"`

	// Details of credit notes that have been applied to an invoice
	CreditNotes []CreditNote `json:"CreditNotes,omitempty"`
}
